# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
controllersTest:
    path: /
    controller: App\Controller\BoxMessageController::index